### ISSUE TITLE
Babel + Build System

### ISSUE THREAD

**Issue by amovah** [IonicaBizau/gh-notifier#3]
Hi,

I think, It's better to use [Babel](http://babeljs.io/) to write ES6 or ES7, and convert that to ES5. then everyone with any version of node can use with no error and no issue.

and it's might be good idea, to use a build system. I recommend you [Gulp](https://github.com/gulpjs/gulp) or [Grunt](http://gruntjs.com).

**Comment by IonicaBizau** [comment]
@amovah Babel is great and I do use it when creating bundles for the client because there are more people using old browsers.

In case of Node, I chose to use ES6 natively supported features. People should upgrate to latest versions of Node anyway because of the security issues.

For people using `>=4.0.0` these modules should work smoothly.

And I'm not a fan of Gulp and Grunt... :joy:

**Comment by amovah** [comment]
I think it's time to make people to upgrade their stuff. anyway thank you to notice me that.

**Comment by IonicaBizau** [comment]
What worries me, actually, is having Gulp/Babel/Grunt config files in each little small I build. For Babel I have a global configuration that just makes the code compatible with ES5.
